### ISSUE TITLE
fastload and pathing issue should be dissabled

### ISSUE THREAD

**Issue by shortthefomo** [crypticrabbit/rippled-examples#2]
https://github.com/crypticrabbit/rippled-examples/blob/5e34a5d40d55f21dc2fbf402fd76310b35db2344/rippled.cfg#L191

fast load is not advised for node that run pathing https://github.com/XRPLF/rippled/issues/4224

your suggested settings are saying that the node has pathing enabled and fastload.

**Comment by jscottbranson** [comment]
Thank you so much for the heads up on that, I'll comment accordingly.

I think fast_load can still be useful for nodes with path finding disabled, unless someone has evidence to the contrary?
